Vagrant.configure("2") do |config|
	# Встановлюємо образ Ubuntu
	config.vm.box = "bento/ubuntu-22.04"
	config.vm.network "public_network"
  
	# Налаштування папки спільного доступу
	config.vm.synced_folder ".", "/vagrant", disabled: false

	config.vm.network "forwarded_port", guest: 5230, host: 8080

  
	# Налаштування постійного підключення до бази даних
	config.vm.provision "shell", inline: <<-SHELL
	  # Оновлюємо систему
	  apt-get update
	  apt-get upgrade -y
  
	  # Встановлюємо необхідні пакети
	  apt-get install -y apt-transport-https ca-certificates curl software-properties-common

	  # Add Microsoft package repository
	  # Add Microsoft package repository
	  wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
	  sudo dpkg -i packages-microsoft-prod.deb
	  rm packages-microsoft-prod.deb

	  # Install .NET SDK 8.0
	  sudo apt-get update
	  sudo apt-get install -y dotnet-sdk-8.0
  
	  # Встановлюємо Nginx
	  apt-get install -y nginx
	  systemctl enable nginx
	  systemctl start nginx
	SHELL
  end
  