Vagrant.configure("2") do |config|
  # Встановлюємо образ Ubuntu
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.network "public_network"

  # Налаштування папки спільного доступу
  config.vm.synced_folder ".", "/vagrant", disabled: false

  config.vm.network "forwarded_port", guest: 5230, host: 8080

  # Налаштування постійного підключення до бази даних
  config.vm.provision "shell", inline: <<-SHELL
    # Оновлюємо систему
    apt-get update
    apt-get upgrade -y

    # Встановлюємо необхідні пакети
    apt-get install -y apt-transport-https ca-certificates curl software-properties-common

    # Встановлюємо PostgreSQL
    sudo apt-get install -y postgresql postgresql-contrib

    # Запускаємо PostgreSQL та налаштовуємо його для автоматичного запуску
    sudo systemctl enable postgresql
    sudo systemctl start postgresql

    # Створюємо базу даних і користувача
    sudo -u postgres psql -c "CREATE DATABASE kpp;"
    sudo -u postgres psql -c "CREATE USER postgres WITH PASSWORD 'postgres';"
    sudo -u postgres psql -c "ALTER ROLE postgres SET client_encoding TO 'utf8';"
    sudo -u postgres psql -c "ALTER ROLE postgres SET default_transaction_isolation TO 'read committed';"
    sudo -u postgres psql -c "ALTER ROLE postgres SET timezone TO 'UTC';"
    sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE kpp TO postgres;"

    # Налаштовуємо доступ до PostgreSQL з будь-якої адреси
    sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = 'localhost'/g" /etc/postgresql/14/main/postgresql.conf.pg_hba
    echo "host    all             all             127.0.0.1/32            md5" | sudo tee -a /etc/postgresql/14/main/pg_hba.conf

    # Перезапускаємо PostgreSQL для застосування змін
    sudo systemctl restart postgresql

    # Налаштування часового поясу на (GMT+7)
    sudo timedatectl set-timezone Asia|UTC
    
    # Запускаємо міграції
    cd ../../vagrant/DBWebApp
    dotnet ef database update
    
    # Запускаємо проект
    cd ../WebApplication
    dotnet run
  SHELL
end
